src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;
    
    #[ORM\Column(length: 180)]
    private ?string $role = null;
    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\EqualTo(propertyPath:"Confirmation")]
    private ?string $password = null;

    #[Assert\EqualTo(propertyPath:"password")]
    public ?string $Confirmation = null;

    #[ORM\Column(length: 20)]
    private ?string $Nom = null;

    #[ORM\Column(length: 20)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 30)]
    private ?string $Adresse = null;

    #[ORM\Column(length: 5)]
    private ?string $Sexe = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateDeNaissance = null;

    #[ORM\OneToMany(mappedBy: 'Enseigner', targetEntity: Matiere::class)]
    private Collection $matieres;

    private ?string $Full;

    #[ORM\OneToMany(mappedBy: 'achat', targetEntity: Facture::class)]
    private Collection $factures;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Fichier::class)]
    private Collection $fichiers;

    #[ORM\OneToMany(mappedBy: 'auteur', targetEntity: Comment::class)]
    private Collection $comments;

    

  
    public function __construct(){
        $this->roles = array();
        $this->Enseigner = new ArrayCollection();
        $this->matieres = new ArrayCollection();
        $this->factures = new ArrayCollection();
        $this->fichiers = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRole()
    {
        $role = $this->role;
        // guarantee every user at least has ROLE_USE
        return $role;
    }

    public function setRole($role): self
    {
        $this->role = $role;
        return $this;
    }
    public function getRoles():array
    {
        return array($this->role);
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(string $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->DateDeNaissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $DateDeNaissance): self
    {
        $this->DateDeNaissance = $DateDeNaissance;

        return $this;
    }

    /**
     * @return Collection<int, Matiere>
     */
    public function getMatieres(): Collection
    {
        return $this->matieres;
    }

    public function addMatiere(Matiere $matiere): self
    {
        if (!$this->matieres->contains($matiere)) {
            $this->matieres[] = $matiere;
            $matiere->setEnseigner($this);
        }

        return $this;
    }

    public function removeMatiere(Matiere $matiere): self
    {
        if ($this->matieres->removeElement($matiere)) {
            // set the owning side to null (unless already changed)
            if ($matiere->getEnseigner() === $this) {
                $matiere->setEnseigner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setAchat($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getAchat() === $this) {
                $facture->setAchat(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Fichier>
     */
    public function getFichiers(): Collection
    {
        return $this->fichiers;
    }

    public function addFichier(Fichier $fichier): self
    {
        if (!$this->fichiers->contains($fichier)) {
            $this->fichiers[] = $fichier;
            $fichier->setUser($this);
        }

        return $this;
    }

    public function removeFichier(Fichier $fichier): self
    {
        if ($this->fichiers->removeElement($fichier)) {
            // set the owning side to null (unless already changed)
            if ($fichier->getUser() === $this) {
                $fichier->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuteur($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuteur() === $this) {
                $comment->setAuteur(null);
            }
        }

        return $this;
    }
   
}

src/Controller/EnseignantController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Fichier;
use App\Entity\Matiere;
use App\Entity\Comment;
use App\Form\FichierType;
use App\Form\CommentType;
use App\Repository\MatiereRepository;
use App\Repository\FichierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Service\FileUploader;


class EnseignantController extends AbstractController
{
    #[Route('/enseignant', name: 'app_enseignant')]
    public function index(MatiereRepository $MatiereRepo): Response
    {
        $user= $this->getUser();
        $id = $user->getId();
        $Matiere =$MatiereRepo->findBy(['Enseigner'=>$id]);

        return $this->render('enseignant/index.html.twig', [
            'controller_name' => 'EnseignantController',
            'Matiere' => $Matiere
        ]);
    }

    #[Route('/enseignant/envoye/{{id}}', name: 'enseignant_fichier')]
    public function envoie(Matiere $Matiere,$id,Request $request,EntityManagerInterface $manager,SluggerInterface $slugger,FileUploader $fileUploader): Response
    {
        $user = $this->getUser();

        $Fichier = new Fichier();
        $form = $this->createForm(FichierType::class, $Fichier);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $FichierFile = $form->get('fichier')->getData();

            if ($FichierFile) {
                $FichierFileName = $fileUploader->upload($FichierFile);
                $Fichier->setFichier($FichierFileName);
            }
            
            $Fichier->setUser($user)
                    ->setMatiere($Matiere);
    
            $manager->persist($Fichier);
            $manager->flush();
        }

        return $this->render('enseignant/fichier.html.twig', [
            'controller_name' => 'EnseignantController',
            'formFichier' => $form->createView(),
            'matiere' => $Matiere,
            'user'=>$user
        ]);
    }
    #[Route('/enseignant/{{id}}', name: 'app_videoEnseignant')]
    public function enseignantVid(Fichier $Fichier,MatiereRepository $MatiereRepo,FichierRepository $FichierRepo,$id,Request $request,EntityManagerInterface $manager): Response
    {
        $Fich = $FichierRepo->find($id);
        $user = $this->getUser();

        $Comment = new Comment();
        $form = $this->createForm(CommentType::class, $Comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $Comment->setCreatedAt(new \DateTimeImmutable)
                    ->setAuteur($user)
                    ->setFich($Fichier);
    
            $manager->persist($Comment);
            $manager->flush();
        }

        return $this->render('enseignant/videoEnseignant.html.twig', [
            'controller_name' => 'EtudiantController',
            'formComment' => $form->createView(),
            'fich' => $Fich,
            'fichier'=>$Fichier,
            'user'=>$user
        ]);
    }
       
}

templates/enseignant/fichier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('css/produit.css')}}">
{% endblock %}
{% block header %}
<div class="brand">
    <h1>Envoyer votre fichier</h1>
</div>
{% endblock %}
{% block body %}
<article>
  <div class="content">
      <h2>{{user.Nom}}</h2>     
      <h2>{{matiere.NomMat}}</h2>
  </div>
</article>
  <h2>Publication d'une nouvelle video:</h2>
  <p><i>Veuillez choisir des fichier video inferieur a 40Mo!!!</i></p>
  {{form_start(formFichier)}}
        <div class="form-group">
        {{form_widget(formFichier.nomFichier,{'attr':{'class':"form-control"}})}}
        </div>
        <div class="form-group">
               {{form_widget(formFichier.fichier,{'attr':{'class':"form-control"}})}}
          </div>
        <button type="submit" class="btn btn-primary">
          publier
        </button>
  {{form_end(formFichier)}}
<div class="row row-cols-1 row-cols-md-3">
  {%for fichier in matiere.fichiers%}    
        <div class="col mb-4">
            <div class="card">
                <div class="card-body">        
                    <video width="320" height="240" controls>
                        <source src="/uploads/{{fichier.fichier}}" type="video/mp4">
                    Your browser does not support the video tag.
                    </video> 
                </div>
                <div class="card-footer">
                    <form method="POST" action="{{path("app_videoEnseignant",{id:fichier.Id})}}" style="display:inline-block">
                        <input type="hidden" name="_token" value="{{csrf_token('fichier' ~ fichier.Id)}}">
                        <input type="hidden" name="_method" value="fichier">
                        <button class="btn btn-sm btn-outline-danger vid">{{fichier.nomFichier}}</button>
                    </form>
                </div>
            </div>

        </div>
    {% endfor %}
</div>
{% endblock %}

templates/enseignant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EnseignantController!{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('css/produit.css')}}">
{% endblock %}
{% block header %}
<div class="brand">
    <h1>Enseigner</h1>
</div>
{% endblock %}
{% block body %}
<div class="row row-cols-1 row-cols-md-3">
    {%for Matieres in Matiere%}
        <div class="col mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Votre formation en {{Matieres.NomMat}}</h5>
                    <form method="POST" action="{{path("enseignant_fichier",{id:Matieres.Id})}}" style="display:inline-block">
                        <input type="hidden" name="_token" value="{{csrf_token('matiere' ~ Matieres.Id)}}">
                        <input type="hidden" name="_method" value="matiere">
                        <button class="btn btn-sm btn-outline-danger">{{Matieres.NomMat}}</button>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
  </div>
<a href="https://meet.google.com/">GOOGLE MEET</a>
{% endblock %}

templates/enseignant/videoEnseignant.html.twig
{% extends 'base.html.twig' %}

{% block title %}produits{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{asset('css/comment.css')}}">
{% endblock %}
{% block body %}
</br></br>
<div class="row mb-6">
    <div class="col-md-8">
        <video width="620" height="340" controls>
            <source src="/uploads/{{fich.fichier}}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <h1 class="mt-3">{{fich.nomFichier}}</h1>
        <a href='/uploads/{{fich.fichier}}'>Telecharger</a>
        <h2>Commentaire:</h2>
        {{form_start(formComment)}}
              <div class="form-group">
                     {{form_widget(formComment.commentaire,{'attr':{'class':"form-control"}})}}
                </div>
              <button type="submit" class="btn btn-primary">
                publier
              </button>
        {{form_end(formComment)}}
    </div>    
    <div class="col-md-4 border over">
            {%for comment in fich.Comments%}
            <div class="container">
             <h5 class="use"><i>{{user.nom}}{{comment.createdAt|date('d/m/y')}}:</i></h5><small>{{comment.commentaire}}</small>
             </br></br>
            </div> 
         {% endfor %}
    </div>
</div>
{% endblock %}